name: gpt-for-data2
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - transformers
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
      - openai
